Added vulnerability check for Exercise_13b.

diff --git a/.github/workflows/check-vulnerabilities.yml b/.github/workflows/check-vulnerabilities.yml
--- a/.github/workflows/check-vulnerabilities.yml
+++ b/.github/workflows/check-vulnerabilities.yml
@@ -21,11 +21,11 @@ jobs:
       with:
         dotnet-version: '8.0'  
 
-    - name: Restore dependencies
+    - name: Restore dependencies for Exercise_31a
       working-directory: ./Exercise_31a
       run: dotnet restore
 
-    - name: List vulnerable packages
+    - name: List vulnerable packages for Exercise_31a
       working-directory: ./Exercise_31a
       run: |
         # Capture the output of the command into a variable
@@ -35,9 +35,30 @@ jobs:
         echo "$output"
         
         # Check if any vulnerabilities were found
-        if [[ "$output" == *"No vulnerable packages found"* ]]; then
-          echo "No vulnerabilities found."
-        else
+        if [[ "$output" == *"has the following vulnerable packages"* ]]; then
           echo "Vulnerabilities found!"
           exit 1  # Fail the workflow
+        else
+          echo "No vulnerabilities found."
+        fi
+
+    - name: Restore dependencies for Exercise_13b
+      working-directory: ./Exercise_13b
+      run: dotnet restore
+
+    - name: List vulnerable packages for Exercise_13b
+      working-directory: ./Exercise_13b
+      run: |
+        # Capture the output of the command into a variable
+        output=$(dotnet list package --vulnerable)
+        
+        # Output the result to the GitHub Actions logs
+        echo "$output"
+        
+        # Check if any vulnerabilities were found
+        if [[ "$output" == *"has the following vulnerable packages"* ]]; then
+          echo "Vulnerabilities found!"
+          exit 1  # Fail the workflow
+        else
+          echo "No vulnerabilities found."
         fi
